import React from 'react';
import VizAwareImg from './VizAwareImage';

function Goals(props) {
  return (
    <div>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id massa eu mi sagittis mattis sagittis a urna. Vivamus interdum dapibus magna et tincidunt. Aenean neque magna, faucibus eu sodales ut, convallis et magna. Vestibulum condimentum non libero non malesuada. Mauris ornare pretium est, vel lacinia lectus efficitur eget. Aliquam erat volutpat. Suspendisse eu magna nibh. Nullam blandit tortor non diam elementum porta. Proin aliquet luctus orci sit amet egestas. In hac habitasse platea dictumst. Curabitur sollicitudin pretium lobortis. Fusce pulvinar condimentum pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius vulputate iaculis. Nunc risus risus, gravida vitae velit at, imperdiet bibendum ex. Aenean gravida interdum ante et laoreet.
        <VizAwareImg src="https://media.wired.com/photos/5a593a7ff11e325008172bc2/125:94/w_2393,h_1800,c_limit/pulsar-831502910.jpg" side="left" />
        {' '}
        Etiam vitae scelerisque erat. Maecenas rutrum orci massa, eget convallis lectus congue vitae. Pellentesque porttitor sapien ut sodales facilisis. In et ultrices nunc. Quisque fermentum mauris tempor aliquet sollicitudin. Praesent fermentum dui ut neque sodales, nec laoreet diam aliquet. Nullam enim quam, consequat eget dui ac, vehicula condimentum diam. Aliquam interdum facilisis nunc, sed lobortis dolor. Proin elementum neque non ullamcorper mattis. Donec a sollicitudin magna.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id massa eu mi sagittis mattis sagittis a urna. Vivamus interdum dapibus magna et tincidunt. Aenean neque magna, faucibus eu sodales ut, convallis et magna. Vestibulum condimentum non libero non malesuada. Mauris ornare pretium est, vel lacinia lectus efficitur eget. Aliquam erat volutpat. Suspendisse eu magna nibh. Nullam blandit tortor non diam elementum porta. Proin aliquet luctus orci sit amet egestas. In hac habitasse platea dictumst. Curabitur sollicitudin pretium lobortis. Fusce pulvinar condimentum pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius vulputate iaculis. Nunc risus risus, gravida vitae velit at, imperdiet bibendum ex. Aenean gravida interdum ante et laoreet.
        <VizAwareImg src="https://media2.govtech.com/images/940*630/Space1.jpg" side="right" />
        {' '}
        Phasellus ac magna tincidunt, convallis nibh ac, suscipit urna. Praesent non vestibulum lorem, quis suscipit nunc. Nulla et tempus leo. Duis sodales arcu a libero dignissim, venenatis consectetur orci condimentum. Pellentesque elementum tristique tortor in bibendum. Cras a pulvinar lacus. Morbi vestibulum, eros eu vulputate egestas, mi nisl mattis magna, id faucibus felis ligula eget purus. Sed congue massa quis eros fermentum, eu semper enim sollicitudin. Suspendisse ac eros aliquam, bibendum leo sit amet, hendrerit nisi. Nullam odio mi, semper id pretium nec, vulputate et tellus. Nullam vel lobortis justo, vel imperdiet nibh. Maecenas ut tempus arcu, a tristique risus
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id massa eu mi sagittis mattis sagittis a urna. Vivamus interdum dapibus magna et tincidunt. Aenean neque magna, faucibus eu sodales ut, convallis et magna. Vestibulum condimentum non libero non malesuada. Mauris ornare pretium est, vel lacinia lectus efficitur eget. Aliquam erat volutpat. Suspendisse eu magna nibh. Nullam blandit tortor non diam elementum porta. Proin aliquet luctus orci sit amet egestas. In hac habitasse platea dictumst. Curabitur sollicitudin pretium lobortis. Fusce pulvinar condimentum pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius vulputate iaculis. Nunc risus risus, gravida vitae velit at, imperdiet bibendum ex. Aenean gravida interdum ante et laoreet.
        <VizAwareImg src="https://www.abc.net.au/cm/rimage/10078922-3x2-large.jpg" side="left" />
        {' '}
        Vivamus ornare, tortor eget tempor placerat, ex lorem sagittis ipsum, at pharetra lorem leo eu nulla. Maecenas in ex condimentum, ornare neque in, luctus erat. Aliquam pellentesque arcu eros, a euismod felis egestas ut. Duis vel maximus ante, id sollicitudin est. Nunc lacus neque, sodales in sem sit amet, cursus interdum felis. Quisque scelerisque urna ut vehicula venenatis. Phasellus ac maximus magna, rhoncus rutrum felis. Ut hendrerit varius finibus. Donec eget vehicula neque. Maecenas quis tortor in metus feugiat rutrum eu eu leo.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id massa eu mi sagittis mattis sagittis a urna. Vivamus interdum dapibus magna et tincidunt. Aenean neque magna, faucibus eu sodales ut, convallis et magna. Vestibulum condimentum non libero non malesuada. Mauris ornare pretium est, vel lacinia lectus efficitur eget. Aliquam erat volutpat. Suspendisse eu magna nibh. Nullam blandit tortor non diam elementum porta. Proin aliquet luctus orci sit amet egestas. In hac habitasse platea dictumst. Curabitur sollicitudin pretium lobortis. Fusce pulvinar condimentum pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla varius vulputate iaculis. Nunc risus risus, gravida vitae velit at, imperdiet bibendum ex. Aenean gravida interdum ante et laoreet.
        <VizAwareImg src="https://www.scitecheuropa.eu/wp-content/uploads/2019/10/Space-Race-1068x601.jpg" side="right" />
        {' '}
        Pellentesque porttitor enim quis tincidunt vestibulum. Aliquam blandit, quam ac aliquet finibus, ipsum turpis porttitor purus, et congue leo urna eu nibh. Proin vel sollicitudin enim. Aenean pretium sit amet ligula quis bibendum. Donec tincidunt eu nunc eu pretium. Praesent eu orci maximus, dignissim nulla eu, feugiat enim. Nullam luctus nunc lorem, sit amet aliquam purus aliquam sit amet. Suspendisse ultricies convallis lorem, in lobortis neque. Quisque a justo cursus, dignissim odio sed, feugiat nibh. Nulla dignissim lacinia ultricies. Ut rutrum turpis sit amet nulla ullamcorper eleifend.
      </p>
    </div>
  );
}

export default Goals;
